#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_mixer
Version  : 1.2.12
Release  : 13
URL      : https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
Summary  : Simple DirectMedia Layer - Sample Mixer Library
Group    : Development/Tools
License  : Artistic-1.0-Perl BSD-3-Clause LGPL-2.0 Zlib
Requires: SDL_mixer-lib = %{version}-%{release}
Requires: SDL_mixer-license = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : flac-dev
BuildRequires : libmodplug-dev
BuildRequires : libogg-dev
BuildRequires : mpg123-dev
BuildRequires : pkgconfig(vorbisfile)

%description
Due to popular demand, here is a simple multi-channel audio mixer.
It supports 4 channels of 16 bit stereo audio, plus a single channel
of music, mixed by the popular MikMod MOD, Timidity MIDI, Ogg Vorbis,
Tremor, SMPEG MP3, and libmad MP3 libraries.

%package dev
Summary: dev components for the SDL_mixer package.
Group: Development
Requires: SDL_mixer-lib = %{version}-%{release}
Provides: SDL_mixer-devel = %{version}-%{release}
Requires: SDL_mixer = %{version}-%{release}

%description dev
dev components for the SDL_mixer package.


%package lib
Summary: lib components for the SDL_mixer package.
Group: Libraries
Requires: SDL_mixer-license = %{version}-%{release}

%description lib
lib components for the SDL_mixer package.


%package license
Summary: license components for the SDL_mixer package.
Group: Default

%description license
license components for the SDL_mixer package.


%prep
%setup -q -n SDL_mixer-1.2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567187639
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --enable-music-ogg \
--enable-music-mp3 \
--enable-music-mod-modplug
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1567187639
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_mixer
cp COPYING %{buildroot}/usr/share/package-licenses/SDL_mixer/COPYING
cp VisualC/external/lib/x64/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.FLAC.txt
cp VisualC/external/lib/x64/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.mikmod.txt
cp VisualC/external/lib/x64/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.ogg-vorbis.txt
cp VisualC/external/lib/x64/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.smpeg.txt
cp VisualC/external/lib/x86/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.FLAC.txt
cp VisualC/external/lib/x86/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.mikmod.txt
cp VisualC/external/lib/x86/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.ogg-vorbis.txt
cp VisualC/external/lib/x86/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.smpeg.txt
cp Xcode/Frameworks/FLAC.framework/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_FLAC.framework_LICENSE.FLAC.txt
cp Xcode/Frameworks/Ogg.framework/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_Ogg.framework_LICENSE.ogg-vorbis.txt
cp Xcode/Frameworks/Vorbis.framework/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_Vorbis.framework_LICENSE.ogg-vorbis.txt
cp Xcode/Frameworks/mikmod.framework/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_mikmod.framework_LICENSE.mikmod.txt
cp Xcode/Frameworks/smpeg.framework/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_smpeg.framework_LICENSE.smpeg.txt
cp timidity/COPYING %{buildroot}/usr/share/package-licenses/SDL_mixer/timidity_COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_mixer.h
/usr/lib64/libSDL_mixer.so
/usr/lib64/pkgconfig/SDL_mixer.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_mixer-1.2.so.0
/usr/lib64/libSDL_mixer-1.2.so.0.12.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_mixer/COPYING
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.FLAC.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.mikmod.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.ogg-vorbis.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x64_LICENSE.smpeg.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.FLAC.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.mikmod.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.ogg-vorbis.txt
/usr/share/package-licenses/SDL_mixer/VisualC_external_lib_x86_LICENSE.smpeg.txt
/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_FLAC.framework_LICENSE.FLAC.txt
/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_Ogg.framework_LICENSE.ogg-vorbis.txt
/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_Vorbis.framework_LICENSE.ogg-vorbis.txt
/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_mikmod.framework_LICENSE.mikmod.txt
/usr/share/package-licenses/SDL_mixer/Xcode_Frameworks_smpeg.framework_LICENSE.smpeg.txt
/usr/share/package-licenses/SDL_mixer/timidity_COPYING
