#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 542402611043
#
Name     : SDL_mixer
Version  : 1.2.12
Release  : 16
URL      : https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-1.2.12.tar.gz
Summary  : Simple DirectMedia Layer - Sample Mixer Library
Group    : Development/Tools
License  : Artistic-1.0-Perl BSD-3-Clause LGPL-2.0 Zlib
Requires: SDL_mixer-lib = %{version}-%{release}
Requires: SDL_mixer-license = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : buildreq-configure
BuildRequires : flac-dev
BuildRequires : libmodplug-dev
BuildRequires : libogg-dev
BuildRequires : mpg123-dev
BuildRequires : pkgconfig(fluidsynth)
BuildRequires : pkgconfig(libmikmod)
BuildRequires : pkgconfig(vorbisfile)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Due to popular demand, here is a simple multi-channel audio mixer.
It supports 4 channels of 16 bit stereo audio, plus a single channel
of music, mixed by the popular MikMod MOD, Timidity MIDI, Ogg Vorbis,
Tremor, SMPEG MP3, and libmad MP3 libraries.

%package dev
Summary: dev components for the SDL_mixer package.
Group: Development
Requires: SDL_mixer-lib = %{version}-%{release}
Provides: SDL_mixer-devel = %{version}-%{release}
Requires: SDL_mixer = %{version}-%{release}

%description dev
dev components for the SDL_mixer package.


%package lib
Summary: lib components for the SDL_mixer package.
Group: Libraries
Requires: SDL_mixer-license = %{version}-%{release}

%description lib
lib components for the SDL_mixer package.


%package license
Summary: license components for the SDL_mixer package.
Group: Default

%description license
license components for the SDL_mixer package.


%prep
%setup -q -n SDL_mixer-1.2.12
cd %{_builddir}/SDL_mixer-1.2.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1732126743
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --enable-music-ogg \
--enable-music-mp3 \
--enable-music-mod-modplug
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1732126743
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_mixer
cp %{_builddir}/SDL_mixer-%{version}/COPYING %{buildroot}/usr/share/package-licenses/SDL_mixer/d7f0884777ded9bd4524a212b8e5b6dce8476114 || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x64/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/500bbacec5d91f0bbdf53a86846bb3a3e5026283 || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x64/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/4d30d8332a334f2b91442d05c0bb7c17850c2bdc || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x64/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/45177cdb4b0a4675541af8784ef0f11a574b646d || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x64/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/bfb8c297e167d90d655d79df6962ddf81d99072c || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x86/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/500bbacec5d91f0bbdf53a86846bb3a3e5026283 || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x86/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/4d30d8332a334f2b91442d05c0bb7c17850c2bdc || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x86/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/45177cdb4b0a4675541af8784ef0f11a574b646d || :
cp %{_builddir}/SDL_mixer-%{version}/VisualC/external/lib/x86/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/bfb8c297e167d90d655d79df6962ddf81d99072c || :
cp %{_builddir}/SDL_mixer-%{version}/Xcode/Frameworks/FLAC.framework/LICENSE.FLAC.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/11464e106e37066a94a23fe4912581799daa3e41 || :
cp %{_builddir}/SDL_mixer-%{version}/Xcode/Frameworks/Ogg.framework/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/4406aeb00f12a2c9cfba8066eef1a7a0c9b32f43 || :
cp %{_builddir}/SDL_mixer-%{version}/Xcode/Frameworks/Vorbis.framework/LICENSE.ogg-vorbis.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/4406aeb00f12a2c9cfba8066eef1a7a0c9b32f43 || :
cp %{_builddir}/SDL_mixer-%{version}/Xcode/Frameworks/mikmod.framework/LICENSE.mikmod.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/44f7289042b71631acac29b2f143330d2da2479e || :
cp %{_builddir}/SDL_mixer-%{version}/Xcode/Frameworks/smpeg.framework/LICENSE.smpeg.txt %{buildroot}/usr/share/package-licenses/SDL_mixer/5fb362ef1680e635fe5fb212b55eef4db9ead48f || :
cp %{_builddir}/SDL_mixer-%{version}/timidity/COPYING %{buildroot}/usr/share/package-licenses/SDL_mixer/73cf7f25e9333afd31ef83960d2e0c94e986f3c5 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_mixer.h
/usr/lib64/libSDL_mixer.so
/usr/lib64/pkgconfig/SDL_mixer.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_mixer-1.2.so.0
/usr/lib64/libSDL_mixer-1.2.so.0.12.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_mixer/11464e106e37066a94a23fe4912581799daa3e41
/usr/share/package-licenses/SDL_mixer/4406aeb00f12a2c9cfba8066eef1a7a0c9b32f43
/usr/share/package-licenses/SDL_mixer/44f7289042b71631acac29b2f143330d2da2479e
/usr/share/package-licenses/SDL_mixer/45177cdb4b0a4675541af8784ef0f11a574b646d
/usr/share/package-licenses/SDL_mixer/4d30d8332a334f2b91442d05c0bb7c17850c2bdc
/usr/share/package-licenses/SDL_mixer/500bbacec5d91f0bbdf53a86846bb3a3e5026283
/usr/share/package-licenses/SDL_mixer/5fb362ef1680e635fe5fb212b55eef4db9ead48f
/usr/share/package-licenses/SDL_mixer/73cf7f25e9333afd31ef83960d2e0c94e986f3c5
/usr/share/package-licenses/SDL_mixer/bfb8c297e167d90d655d79df6962ddf81d99072c
/usr/share/package-licenses/SDL_mixer/d7f0884777ded9bd4524a212b8e5b6dce8476114
